services:
  fantom-website:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fantom-website
    restart: unless-stopped
    networks:
      - webnet

networks:
  webnet:
    external: true
